# Generated by Django 2.1.9 on 2020-02-18 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0019_auto_20200218_2155'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CronTabMain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, '已完成'), (1, '进行中'), (2, '未开始')], default=2, help_text='定时任务添加后，未完成状态，当开始执行任务时 进行中，任务已完结时 已完成')),
                ('key_school', models.ForeignKey(help_text='所关联的班级', on_delete=django.db.models.deletion.CASCADE, to='account.SchoolInfo')),
            ],
        ),
        migrations.CreateModel(
            name='CronTabUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, '已完成'), (1, '进行中'), (2, '未开始')], default=2, help_text='学员任务确定后，未开始状态，当学员开始执行任务时 进行中，任务已完结时 已完成')),
                ('key', models.ForeignKey(help_text='班级任务表', on_delete=django.db.models.deletion.CASCADE, to='exam.CronTabMain')),
                ('key_user', models.ForeignKey(help_text='用户', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
