# Generated by Django 2.1.9 on 2020-02-05 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CronTabConfigs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('times', models.CharField(help_text='定时任务crontab的时间设置格式', max_length=5)),
                ('status', models.IntegerField(blank=True, choices=[(0, 'crontab.run.CronTabExam.run'), (1, 'crontab.run.CronTabTest.run')], null=True)),
                ('run', models.IntegerField(choices=[(0, '考试周期'), (1, '测试周期')], unique=True)),
            ],
        ),
    ]
