# Generated by Django 2.1.9 on 2020-01-28 16:02

from django.db import migrations, models
import django.db.models.deletion
import question.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassQuesChapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='章节分类名称', max_length=150)),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClassQuesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='模块分类名称', max_length=150)),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClassQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='书名分类名称', max_length=150)),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='题型名称', max_length=150, null=True)),
                ('text', models.TextField(help_text='题目描述')),
                ('state', models.IntegerField(choices=[(0, '选择题'), (1, '判断题'), (2, '简答题'), (3, '机试题')], default=0, help_text='类型')),
                ('image', models.ImageField(blank=True, help_text='题型说明图', null=True, upload_to=question.models.Question.get_upload_to)),
                ('key_class_ques_chapter', models.ForeignKey(help_text='章节分类 [书名分类-模块分类-章节分类:选择题|判断题|简答题|机试题]', on_delete=django.db.models.deletion.CASCADE, to='question.ClassQuesChapter', verbose_name='章节分类')),
                ('key_class_ques_model', models.ForeignKey(help_text='模块分类 [书名分类-模块分类-章节分类:选择题|判断题|简答题|机试题]', on_delete=django.db.models.deletion.CASCADE, to='question.ClassQuesModel', verbose_name='模块分类')),
                ('key_class_question', models.ForeignKey(help_text='书名分类 [书名分类-模块分类-章节分类:选择题|判断题|简答题|机试题]', on_delete=django.db.models.deletion.CASCADE, to='question.ClassQuestion', verbose_name='书名分类')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, help_text='得分', max_digits=5, verbose_name='得分')),
                ('solu', models.BooleanField(default=False, help_text='是否是正确答案', verbose_name='正确答案')),
                ('choice_gid', models.IntegerField(blank=True, choices=[(0, 'A'), (1, 'B'), (2, 'C'), (3, 'D'), (4, 'E'), (5, 'F'), (6, 'G')], help_text='选择题标号', null=True, verbose_name='标号')),
                ('choice', models.TextField(blank=True, help_text='选择题答案', null=True, verbose_name='选择题')),
                ('judge', models.IntegerField(blank=True, choices=[(0, '对'), (1, '错'), (2, '全对'), (3, '全错')], help_text='判断题答案', null=True, verbose_name='判断题')),
                ('answer', models.TextField(blank=True, help_text='简答题答案', null=True, verbose_name='简答题')),
                ('machine', models.TextField(blank=True, help_text='机试题答案', null=True, verbose_name='机试题')),
                ('key_question', models.ForeignKey(help_text='答案 [选择题|判断题|简答题|机试题]', on_delete=django.db.models.deletion.CASCADE, to='question.Question', verbose_name='答案')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='classquesmodel',
            name='key_class_question',
            field=models.ForeignKey(help_text='书名分类 [书名分类-模块分类-章节分类:选择题|判断题|简答题|机试题]', on_delete=django.db.models.deletion.CASCADE, to='question.ClassQuestion', verbose_name='书名分类'),
        ),
        migrations.AddField(
            model_name='classqueschapter',
            name='key_class_ques_model',
            field=models.ForeignKey(help_text='模块分类 [书名分类-模块分类-章节分类:选择题|判断题|简答题|机试题]', on_delete=django.db.models.deletion.CASCADE, to='question.ClassQuesModel', verbose_name='模块分类'),
        ),
    ]
