# Generated by Django 2.1.9 on 2020-01-29 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSemester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='书名分类', max_length=150, null=True)),
                ('add_time', models.DateTimeField(auto_now_add=True, help_text='开始学习时间')),
                ('end_time', models.DateTimeField(blank=True, help_text='学习结束时间', null=True)),
                ('key_class_question', models.ForeignKey(help_text='书名分类 [书名分类-模块分类-章节分类:选择题|判断题|简答题|机试题]', on_delete=django.db.models.deletion.CASCADE, to='question.ClassQuestion', verbose_name='书名分类')),
            ],
        ),
    ]
