# Generated by Django 2.1.9 on 2020-02-09 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0010_auto_20200201_1911'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
