# Generated by Django 2.1.5 on 2020-01-14 15:19

from django.db import migrations, models
import wechat.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserWeiXin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribe', models.IntegerField(choices=[(0, '没有关注该公众号'), (1, '已关注该公众号')], help_text='用户是否订阅该公众号标识，值为0时，代表此用户没有关注该公众号，拉取不到其余信息。')),
                ('openid', models.CharField(help_text='用户的标识，对当前公众号唯一', max_length=50)),
                ('unionid', models.CharField(blank=True, help_text='只有在用户将公众号绑定到微信开放平台帐号后，才会出现该字段。', max_length=50, null=True)),
                ('nickname', models.CharField(help_text='用户的昵称', max_length=50)),
                ('sex', models.IntegerField(choices=[(0, '未知'), (1, '男性'), (2, '女性')], help_text='用户的性别，值为1时是男性，值为2时是女性，值为0时是未知')),
                ('country', models.CharField(help_text='用户所在国家', max_length=20)),
                ('city', models.CharField(help_text='用户所在城市', max_length=20)),
                ('province', models.CharField(help_text='用户所在省份', max_length=20)),
                ('language', models.CharField(help_text='用户的语言，简体中文为zh_CN', max_length=20)),
                ('headimgurl', models.ImageField(help_text='用户头像，最后一个数值代表正方形头像大小（有0、46、64、96、132数值可选，0代表640*640正方形头像），用户没有头像时该项为空。若用户更换头像，原有头像URL将失效。', upload_to=wechat.models.UserWeiXin.image_directory_path)),
                ('subscribe_time', models.DateTimeField(help_text='用户关注时间，为时间戳。如果用户曾多次关注，则取最后关注时间')),
                ('remark', models.TextField(help_text='公众号运营者对粉丝的备注，公众号运营者可在微信公众平台用户管理界面对粉丝添加备注')),
                ('groupid', models.CharField(help_text='用户所在的分组ID（兼容旧的用户分组接口）', max_length=20)),
                ('tagid_list', models.CharField(help_text='用户被打上的标签ID列表', max_length=20)),
                ('subscribe_scene', models.CharField(choices=[('ADD_SCENE_SEARCH', '公众号搜索'), ('ADD_SCENE_ACCOUNT_MIGRATION', '公众号迁移'), ('ADD_SCENE_PROFILE_CARD', '名片分享'), ('ADD_SCENE_QR_CODE', '扫描二维码'), ('ADD_SCENE_PROFILE_ LINK', '图文页内名称点击'), ('ADD_SCENE_PROFILE_ITEM', '图文页右上角菜单'), ('ADD_SCENE_PAID', '支付后关注'), ('ADD_SCENE_OTHERS', '其他')], help_text='返回用户关注的渠道来源', max_length=20)),
                ('qr_scene', models.IntegerField(help_text='二维码扫码场景（开发者自定义）')),
                ('qr_scene_str', models.TextField(help_text='二维码扫码场景描述（开发者自定义）', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='WeixinAccessToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField(blank=True, help_text='获取到的凭证', null=True)),
                ('expires_in', models.IntegerField(blank=True, help_text='凭证有效时间，单位：秒', null=True)),
                ('errcode', models.IntegerField(choices=[(-1, '系统繁忙，此时请开发者稍候再试'), (0, '请求成功'), (40001, 'AppSecret错误或者AppSecret不属于这个公众号，请开发者确认AppSecret的正确性'), (40002, '请确保grant_type字段值为client_credential'), (40164, '调用接口的IP地址不在白名单中，请在接口IP白名单中进行设置。（小程序及小游戏调用不要求IP地址在白名单内。）')], default=0, help_text='返回错误码')),
                ('errmsg', models.TextField(blank=True, help_text='返回错误信息', null=True)),
                ('time', models.DateTimeField(auto_now_add=True, help_text='添加时间')),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
    ]
