# Generated by Django 2.1.9 on 2020-02-04 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, '系统设置')], unique=True)),
                ('paging', models.IntegerField(default=20, help_text='前端数据分页')),
            ],
        ),
        migrations.CreateModel(
            name='SystemQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stats', models.IntegerField(choices=[(0, '刷题'), (1, '考试')], unique=True)),
                ('status', models.IntegerField(choices=[(0, '选择题'), (1, '判断题'), (2, '简答题'), (3, '机试题')])),
                ('amount', models.IntegerField(default=10, help_text='题数量')),
            ],
        ),
    ]
