# Generated by Django 2.1.9 on 2020-02-04 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conf', '0003_remove_systemquestion_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemExamControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, '考试周期')], unique=True)),
                ('exam_time', models.IntegerField(help_text='考试周期控制')),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('now_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
